### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by mrgsi** [Zaxxon709/accountmanager#1]
Awesome work you are doing. Thought I'd offer a suggestion to include the "Your Accounts" module from The Warehouse repository. It's a simple fork of "My Accounts" so it should be easy to code. "Your Accounts" is used by Loonatics Empire, Dynasty, Adina and Artemis.

**Comment by Zaxxon709** [comment]
> Awesome work you are doing. Thought I'd offer a suggestion to include the "Your Accounts" module from The Warehouse repository. It's a simple fork of "My Accounts" so it should be easy to code. "Your Accounts" is used by Loonatics Empire, Dynasty, Adina and Artemis.

Thanks for the positive feedback. I wasn't planning on adding anything else due to the increase in API requests. We'll see how everything holds up for now.

**Comment by kolekan** [comment]
> > Awesome work you are doing. Thought I'd offer a suggestion to include the "Your Accounts" module from The Warehouse repository. It's a simple fork of "My Accounts" so it should be easy to code. "Your Accounts" is used by Loonatics Empire, Dynasty, Adina and Artemis.
> 
> Thanks for the positive feedback. I wasn't planning on adding anything else due to the increase in API requests. We'll see how everything holds up for now.

Concerning about api requests ,it wil help an option of using custom user api keys in your script. So Kodi builders get their api keys and use it with this script.

**Comment by Zaxxon709** [comment]
> > 
> > ......I wasn't planning on adding anything else due to the increase in API requests. We'll see how everything holds up for now.
> 
> Concerning about api requests ,it wil help an option of using custom user api keys in your script. So Kodi builders get their api keys and use it with this script.

Yes, I agree! When time allows I will be looking into adding custom keys as an option. However, only a handful of users will actually use their own keys. 99% of users will auth and use Account Manager keys. If any issues arise in the near future I may have to make this addon only useable with custom/user keys.
