### ISSUE TITLE
Configure backup directory on SMB://

### ISSUE THREAD

**Issue by hyc** [Zaxxon709/accountmanager#11]
I'd like to be able to use my local NAS for backup/restore, so I can access it from other machines and not worry about a local path getting wiped out during remove/reinstall. Any chance of being able to just input a path in a text window, instead of browsing the local filesystem?

**Comment by Zaxxon709** [comment]
I'll have a look when time allows...No guarantees. If you choose the right local path you will not have your data deleted during fresh installs or updates. To be honest the data is not that important or rarely needed. You can reauthorize all 
add-ons within a minute or two
"The default path is not persistent after build updates or fresh starts. For builders, I'd recommend your wizard data path for backups. For users, I'd recommend whitelisting your backup directory. If the default path is changed make sure to complete another backup."

**Comment by Zaxxon709** [comment]
I'll have a look when time allows...No guarantees. If you choose the right local path you will not have your data deleted during fresh installs or updates (See below). To be honest the data is not that important or rarely needed. You can reauthorize all add-ons within a minute or two.

"The default path is not persistent after build updates or fresh starts. For builders, I'd recommend your wizard data path for backups. For users, I'd recommend whitelisting your backup directory. If the default path is changed make sure to complete another backup."

**Comment by rowel07** [comment]
@Zaxxon709
Hi. What I should enter in "action" if I wanted to create a shortcut of this addon? Currently using Artic Fuse skin.

**Comment by Zaxxon709** [comment]
> @Zaxxon709 Hi. What I should enter in "action" if I wanted to create a shortcut of this addon? Currently using Artic Fuse skin.

RunAddon(script.module.accountmgr)

**Comment by rowel07** [comment]
> > @Zaxxon709 Hi. What I should enter in "action" if I wanted to create a shortcut of this addon? Currently using Artic Fuse skin.
> 
> RunAddon(script.module.accountmgr)

Thank you so much.
I used Artic Fuse  Options Menu to put some of the command shortcut. But how do I disable the Account Manager settings window to automatically show up?
For example. When I'm trying authorize Trakt then click on cancel or sync Trakt on add-ons?

**Comment by Zaxxon709** [comment]
@rowel07 The post that you're commenting on here was opened previously by another user.

I'm not quite sure what problem you're experiencing but If there is an issue with the addon could you please open a new issue including a detailed description of the problem. Thanks

**Comment by Zaxxon709** [comment]
> I'd like to be able to use my local NAS for backup/restore, so I can access it from other machines and not worry about a local path getting wiped out during remove/reinstall. Any chance of being able to just input a path in a text window, instead of browsing the local filesystem?

Added option to manually add backup directory in v2.3.5
