### ISSUE TITLE
Coalition from Chains repo doesn't get authorized

### ISSUE THREAD

**Issue by cg00001** [Zaxxon709/accountmanager#12]
It's listed but doesn't work.
![coal](https://github.com/Zaxxon709/accountmanager/assets/38960370/de675001-bf15-413d-9d42-6e80fd9c2400)

**Comment by Zaxxon709** [comment]
Unfortunately, I have no idea what you're reporting as an issue. Could you take the time to include a little more detail, please? Maybe then I can try to reproduce the error. 

Is it possible you're using the previous version? The Coalition was added to v2.3.4.

**Comment by cg00001** [comment]
I tried my build first with Kodi Omega and it doesn't authorize it.
I tried another with Kodi Nexus, and again it doesn't authorize it. Both with Account Manager v2.3.4
Maybe -again- it's a Linux issue.
Debrid & Trakt are authorized fine on Coalition from Coalition settings.
On both Kodis v2.3.4 gives an error on every reboot, seems to go away after several reboots.
Error is:
![account](https://github.com/Zaxxon709/accountmanager/assets/38960370/31f74163-2e50-4cd8-8609-88c7dad5a551)

**Comment by Zaxxon709** [comment]
What version of acctview do you have installed?

**Comment by Zaxxon709** [comment]
I suspect you have the previous version installed. I have tested and I am unable to reproduce the issue you have mentioned. Could you confirm and if so install the latest version and test. Then report back, thanks.

**Comment by cg00001** [comment]
> I suspect you have the previous version installed. I have tested and I am unable to reproduce the issue you have mentioned. Could you confirm and if so install the latest version and test. Then report back, thanks.

Thanks a million, my acctview  was still the previous version.
Coalition is easily authorized via a simple sync now.

**Comment by Zaxxon709** [comment]
> > I suspect you have the previous version installed. I have tested and I am unable to reproduce the issue you have mentioned. Could you confirm and if so install the latest version and test. Then report back, thanks.
> 
> Thanks a million, my acctview was still the previous version. Coalition is easily authorized via a simple sync now.

That's great! Glad you got it sorted. Enjoy!
