### ISSUE TITLE
[Request] Addon support

### ISSUE THREAD

**Issue by Sovilor** [Zaxxon709/accountmanager#14]
Hello,
Please add Otaku to the Debrid supported addons.
Thank you.

**Comment by Zaxxon709** [comment]
> Hello, Please add Otaku to the Debrid supported addons. Thank you.

I will add this in the next release

**Comment by Zaxxon709** [comment]
@Sovilor Otaku has been added to this release (Account Manager v2.3.8 / AcctView v2.2.4). Report back if there are any issues, please. Thank you

**Comment by Sovilor** [comment]
@Zaxxon709 just tested, works well.
Thank you.

**Comment by Sovilor** [comment]
AllDebrid info (synced) is showing in Otaku accounts settings, but no results can be found from.

So AllDebrid looks as authorized but technically it's not.

**Comment by Zaxxon709** [comment]
> AllDebrid info (synced) is showing in Otaku accounts settings, but no results can be found from.
> 
> So AllDebrid looks as authorized but technically it's not.

Test using the below

[script.module.accountmgr-2.3.8.zip](https://github.com/Zaxxon709/accountmanager/files/13193790/script.module.accountmgr-2.3.8.zip)
[script.module.acctview-2.2.4.zip](https://github.com/Zaxxon709/accountmanager/files/13193791/script.module.acctview-2.2.4.zip)

**Comment by Sovilor** [comment]
> 
> Test using the below
> 
> [script.module.accountmgr-2.3.8.zip](https://github.com/Zaxxon709/accountmanager/files/13193790/script.module.accountmgr-2.3.8.zip) [script.module.acctview-2.2.4.zip](https://github.com/Zaxxon709/accountmanager/files/13193791/script.module.acctview-2.2.4.zip)

It works.
Thank you
