### ISSUE TITLE
Will Fen Lite ever work with account manager?

### ISSUE THREAD

**Issue by tapwizard** [Zaxxon709/accountmanager#16]
Just wondering if there is a workaround to get fen lite to work with account manager being that fen lite doesn't create a settings.xml even after going through settings. A databases folder is created with a settings.db file. Thanks.

**Comment by Zaxxon709** [comment]
To be honest, I haven't even looked into it. I thought it was still in his test repo but see its not now. It's on my list and when time allows I will take a look.

**Comment by Zaxxon709** [comment]
@tapwizard Fen Light has been added to Account Manager. I noticed the dev did remove it from his repo a few days ago but I decided to still add it.  If you have any issues, please report them. Thanks
