### ISSUE TITLE
v2.4.0 broke umbrella trakt

### ISSUE THREAD

**Issue by Liquidrag** [Zaxxon709/accountmanager#17]
v2.4.0 seems to have broke trakt in umbrella. It keeps asking to re-auth

osx BigSur
omega beta 2

**Comment by Zaxxon709** [comment]
@Liquidrag I cannot reproduce your issue. I've tested on Nexus and Trakt is working fine. Try revoking Trakt via Account Manager and re-auth.

**Comment by Liquidrag** [comment]
@Zaxxon709 tried revoking and it didn't work. I've resorted to auth-ing each addon individually. Also can you check in fen light watched indicators are showing? It didnt on mine but auth-ing individually fixed it.

**Comment by Zaxxon709** [comment]
> @Zaxxon709 tried revoking and it didn't work. I've resorted to auth-ing each addon individually. Also can you check in fen light watched indicators are showing? It didn't on mine but auth-ing individually fixed it.
> 
> Edit: re-authed and seems to be working now. Thank you.

Thanks for the update. So, both Umbrella and Fen Light are now working ok? The Trakt watched indicators are working on my end.

**Comment by Liquidrag** [comment]
@Zaxxon709 Seems like it. If I run into any issues, I'll let you know. Thank you again.

**Comment by Zaxxon709** [comment]
Ok great! You're welcome
