### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by blry12** [Zaxxon709/accountmanager#18]
is new version 2.4.6? it shows 2.2.6

**Comment by Zaxxon709** [comment]
> is new version 2.4.6? it shows 2.2.6

Yes, v2.4.6 is the latest version.

**Comment by blry12** [comment]
Hello Zaxxon, i love your add on and i use it in my build which is called AURAFlix, I am to the scene and I am doing a fork of FEN and my addon is called AURAFlixMedia. Would it be possible to add my addon to your Account Manager. Thank you!

Github is 
[https://github.com/blry12/auraflix](url)

plugin info is 
plugin.video.afm

**Comment by Zaxxon709** [comment]
Thanks for the feedback...I will take a look at your fork and if it gains popularity I will look into adding it in a future update.

**Comment by blry12** [comment]
awesome i appreciate it.
