### ISSUE TITLE
Error in kodi log

### ISSUE THREAD

**Issue by Sovilor** [Zaxxon709/accountmanager#19]
Hello,
This error is always showing in kodi log, 
The addon that mentioned in the log (Hlamder) never been installed.
This is the log (errors only):
https://paste.kodi.tv/ekopakidix.kodi

One more thing, the option of (Account Expiry Notification) is definitely not working for any of the services (RD, PM, AD).
I didn't keep the log before i extended my accounts.

Thank you.

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue and providing a log. I will have a look at this shortly.

**Comment by Zaxxon709** [comment]
So yeah, you're correct.! The Account Expiry Notification has never been working. It appears it was broken when I forked MyAccounts. I have fixed this and also fixed the metadata error. I will push an update including these fixes in the coming days. Thanks again for reporting this.

**Comment by Sovilor** [comment]
Thank you
