### ISSUE TITLE
Alldebrid Error

### ISSUE THREAD

**Issue by Sovilor** [Zaxxon709/accountmanager#2]
Hello, after the recent update 2.2.5,  Alldebrid Sync Add-ons stopped working. 
Account Manager Error
Log file:
https://paste.kodi.tv/ibuvivawic.kodi

Thank you for making this Addon.

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. I just fixed the error and uploaded v2.2.6. Could you please test and report back?

**Comment by Sovilor** [comment]
v2.2.6 Manage Multiple Debrid Sync All Add-ons, All-Debrid Sync Add-ons, are working and no more giving Error message.

Thank you.

**Comment by Zaxxon709** [comment]
> v2.2.6 Manage Multiple Debrid Sync All Add-ons, All-Debrid Sync Add-ons, are working and no more giving Error message.
> 
> Thank you.

That's great! Thanks for testing
