### ISSUE TITLE
Latest update of account manager

### ISSUE THREAD

**Issue by Arthur1967** [Zaxxon709/accountmanager#20]
! don't use this with the build I use it independently with my own add-ons. What is this error? I'm getting with the latest update thank you[image](https://github.com/Zaxxon709/accountmanager/assets/69996032/e6295d64-c01a-416d-840e-5a0e88530866)

**Comment by Zaxxon709** [comment]
Thanks for reporting the error. Could you please install the below and confirm the error has been fixed? Thanks

[script.module.accountmgr-2.4.8.zip](https://github.com/Zaxxon709/accountmanager/files/14365346/script.module.accountmgr-2.4.8.zip)

**Comment by Arthur1967** [comment]
The problem is fixed. It has nothing to do with account manager. Trakt was the issue it was down for a while thank you. Everything is working great.

**Comment by Arthur1967** [comment]
Every time I hit that link you sent, It’s wants me to download

**Comment by Arthur1967** [comment]
I installed it through the repository. Thanks.

**Comment by Arthur1967** [comment]
I do have one other question do you have the zip file for Universal scrapers? I'd like to try that with umbrella. Thank you I don't know if you can or not.
