### ISSUE TITLE
addons loosing their trakt autorizetion

### ISSUE THREAD

**Issue by Audigy35** [Zaxxon709/accountmanager#21]
umbrella and dardis are loosing each time i lauch kodi their trakt autorizetion.

**Comment by Zaxxon709** [comment]
Could you provide a log, please?

**Comment by Audigy35** [comment]
nfo <general>: Account Manager ERROR: TMDbH API Failed!
2024-02-25 19:19:38.486 T:16920 warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal

**Comment by Zaxxon709** [comment]
> nfo : Account Manager ERROR: TMDbH API Failed! 2024-02-25 19:19:38.486 T:16920 warning : CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal

What version of Account Manager & Acctview do you have installed? Could you provide the full log, please?

**Comment by Audigy35** [comment]
account manager 2.4.8 and acctview 2.3.1

**Comment by Zaxxon709** [comment]
> account manager 2.4.8 and acctview 2.3.1

Provide a full log, please.
