### ISSUE TITLE
kodi.tv Omega 21

### ISSUE THREAD

**Issue by ronfrankhill** [Zaxxon709/accountmanager#22]
Just curious. Would the Account Manager be compatible to use in kodi.tv Omega 21 when it's official release? Just asking. I think it has reach release candidate 2.

**Comment by Zaxxon709** [comment]
> Just curious. Would the Account Manager be compatible to use in kodi.tv Omega 21 when it's official release? Just asking. I think it has reach release candidate 2.

Yes, Account Manager is compatible with K21 Omega.
