### ISSUE TITLE
Kodi issues

### ISSUE THREAD

**Issue by KALFK20** [Zaxxon709/accountmanager#23]
Sorry I'm not sure how to print the error log. These screen shots are my issues.
Any help would be much apricated.

Thanks 

![Screenshot (4)](https://github.com/Zaxxon709/accountmanager/assets/105996618/0943eb5c-eed2-4f62-b764-c55eb806b3d7)
![Screenshot (5)](https://github.com/Zaxxon709/accountmanager/assets/105996618/74ed4b92-b5b5-4138-b354-1480955283e3)
![Screenshot (6)](https://github.com/Zaxxon709/accountmanager/assets/105996618/3d054b85-eeaf-412f-aef2-dcd5d7351b84)
![Screenshot (7)](https://github.com/Zaxxon709/accountmanager/assets/105996618/4aaee2c4-d56d-4012-9e7b-3195155c52a4)
![Screenshot (8)](https://github.com/Zaxxon709/accountmanager/assets/105996618/cab84297-d02a-4b45-ba13-4d588f54c454)
![Screenshot (9)](https://github.com/Zaxxon709/accountmanager/assets/105996618/f050bbf6-9d47-4c30-9258-6bf1f6d29b19)
![Screenshot (10)](https://github.com/Zaxxon709/accountmanager/assets/105996618/941f670e-e0ff-49a2-8c11-c9d0a87e8176)
![Screenshot (11)](https://github.com/Zaxxon709/accountmanager/assets/105996618/7d5982b0-06fc-42c5-bb49-16cd1a5cce0f)
![Screenshot (12)](https://github.com/Zaxxon709/accountmanager/assets/105996618/14c1d968-b055-4915-9fbd-729a05001ef8)

**Comment by Zaxxon709** [comment]
Unfortunately, I do not see anything related to Account Manager in the log screenshots you've sent.

What is the nature of your issue. Describe? 

This appears to Diggz build you gave installed. It might be best to post in their support group.
