### ISSUE TITLE
Question & Comment

### ISSUE THREAD

**Issue by JEM11COBRA** [Zaxxon709/accountmanager#24]
First I would like to comment on the XontriX 21 v1.0 build.  I have been using it the last week and it is flawless.  It is clean, neat, and fast! No clutter!!  My question is this:  Is Super Favourites in any of the repositories?   I know how to add it, but would be convenient if in a repository on the build.  Thanks again for the awesome build.

Jerry

**Comment by Zaxxon709** [comment]
Sorry, Xtronix is not my build. That is a build by Funster. I also have no association with super favs. You can find it on github though and install via zip.

**Comment by JEM11COBRA** [comment]
My apologies!  I saw your name and etc. in the Account Manager and just
assumed.  Thanks for responding.

Jerry
