### ISSUE TITLE
Trackt login window

### ISSUE THREAD

**Issue by Rsvengate** [Zaxxon709/accountmanager#26]
Hello. Is there a way to stop the trackt authorize login window from opening every time you scroll past the Tackt portion of the menus? I thought I had it gone but it started again when I reloaded Xenon from the repository instead of just wiping and starting over. I unistalled Kodi and put the build back in and it is still there. I have checked the account manager and a bunch of other places but I can't figure out how to stop the pop up from showing up. Thanks.

**Comment by Zaxxon709** [comment]
You might want to speak to the builder. This doesn't sound like an issue with Account Manager.
