### ISSUE TITLE
real debrid 

### ISSUE THREAD

**Issue by whitestallion1** [Zaxxon709/accountmanager#27]
it says that Real debrid is all authorize .tried movies and shows but nothing comes up..Even dried different builds .it says that i have 445 days left.
![20240604_215300](https://github.com/Zaxxon709/accountmanager/assets/171758128/fad162c6-59e5-4749-9a92-984176b2c08e)
![Screenshot_20240604_220341_Chrome](https://github.com/Zaxxon709/accountmanager/assets/171758128/d171eb3d-4984-4f6d-9a41-4a1e4e9fcc45)
![Screenshot_20240604_220142_Chrome](https://github.com/Zaxxon709/accountmanager/assets/171758128/e063af9d-cf2e-4979-aac0-a13fc80fa5e9)
![Uploading 20240604_215300.jpg…]()
 not working

**Comment by Zaxxon709** [comment]
Sounds like you're missing the scraper packages for your installed addons. This would have nothing to to with Account Manager.
