### ISSUE TITLE
Fusion Build 

### ISSUE THREAD

**Issue by ronfrankhill** [Zaxxon709/accountmanager#28]
Sorry to bother you. Do you have a Reddit account so as to avoid coming to your GitHub? I know that this is the wrong section to ask about above. I want to use the above build in Omega 21 kodi.tv which will be the first time. Does it have umbrella, Fen lite, Quick Silver, Chain Reaction and Jacktook but does it have these in the program section Account Manager, Autoruns, CoCo Scrapers etc.
If not could you install these above. Please. Thanks.

**Comment by Zaxxon709** [comment]
You can install your addons of choice at startup. Cocoscrapers and Account manager are preinstalled.
