### ISSUE TITLE
 2.2.7 Alldebrid Syncing Error

### ISSUE THREAD

**Issue by Sovilor** [Zaxxon709/accountmanager#3]
Hello, after the recent update 2.2.7, Again Alldebrid Sync Add-ons stopped working.
Account Manager Error
Log file:
https://paste.kodi.tv/ekekidazof.kodi
Thank you

**Comment by Zaxxon709** [comment]
> Hello, after the recent update 2.2.7, Again Alldebrid Sync Add-ons stopped working. Account Manager Error Log file: https://paste.kodi.tv/ekekidazof.kodi Thank you

Thanks for reporting the error. I have fixed the error and uploaded v2.2.8. Could you please test and confirm all functions are working? Thank you

**Comment by Sovilor** [comment]
v2.2.8 Manage Multiple Debrid Sync All Add-ons, All-Debrid Sync Add-ons, both options are working and no more giving Error message.

A request (wish), add an option to sinc Meta Accounts API, if possible.

Thank you for your efforts.

**Comment by Zaxxon709** [comment]
Glad it's sorted! Thanks for testing. I will take a look at adding some meta accounts when I have time. No promises though.

**Comment by Sovilor** [comment]
Take your time.
Best regards
