### ISSUE TITLE
acctviewer error, not showing authorized debrid & Trakt logins

### ISSUE THREAD

**Issue by cg00001** [Zaxxon709/accountmanager#31]
Latest acctviewer makes Account Manager not showing authorized debrid & Trakt logins and gives an error.
Authorizing still works though.
![err](https://github.com/Zaxxon709/accountmanager/assets/38960370/4253baa1-90fb-4040-a8f7-c5612a8b7d1c)

![trakt](https://github.com/Zaxxon709/accountmanager/assets/38960370/720ce733-43cb-4502-b74f-00a8f379e51f)

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. I cannot reproduce the error but I have included a fix in the attached zip. Could you please install and confirm the issue is resolved?

[script.module.acctview.zip](https://github.com/user-attachments/files/15952837/script.module.acctview.zip)

**Comment by cg00001** [comment]
> Thanks for reporting the issue. I cannot reproduce the error but I have included a fix in the attached zip. Could you please install and confirm the issue is resolved?
> 
> [script.module.acctview.zip](https://github.com/user-attachments/files/15952837/script.module.acctview.zip)

It works just fine.

**Comment by Zaxxon709** [comment]
Thanks for testing...v2.3.9 update pushed

**Comment by BTB2024** [comment]
Hi Favorites folder is not working when you click on the folder it does not open. Me I create a New Favorites on main menus and the stuff is there it just doesn't open up. In 21 Xontrix non debris build 1.0 or 1.1 both have issues tyTY
