### ISSUE TITLE
Favorites Not working

### ISSUE THREAD

**Issue by BTB2024** [Zaxxon709/accountmanager#32]
Hi Favorites folder is not working when you click on the folder it does not open. Me I create a New Favorites on main menus and the stuff is there it just doesn't open up. TY

**Comment by BTB2024** [comment]
In 21 Xontrix non debris build 1.0 or 1.1 both have issues ty

**Comment by Zaxxon709** [comment]
Sorry, Xtronix is not one of my builds. 

I decided to have a quick look to help you out. The favs in Xtronix are working as intended. I see no issue. You might want to provide a little more detail on what you're trying to do. I'd suspect user error here.
