### ISSUE TITLE
Bug: Adding text to 'Trakt API Key' makes the 'Authorize' button disappear 

### ISSUE THREAD

**Issue by ditydot** [Zaxxon709/accountmanager#34]
Version: 2.5.7

Adding any characters/text to the 'Trakt API Key' value after ticking 'Use Custom Trakt API Keys' on the accounts tab makes the 'Authorize' button disappear. With it being gone you can't proceed to authorise using your own custom keys.

**Comment by Zaxxon709** [comment]
Thanks for reporting. I will look into this.

**Comment by Zaxxon709** [comment]
I will push an update with a fix for this issue in the coming days. Thanks for your patience

**Comment by Zaxxon709** [comment]
An update has been pushed to fix this issue v2.5.8
