### ISSUE TITLE
Trakt on pov and fen not working 

### ISSUE THREAD

**Issue by drewg0407** [Zaxxon709/accountmanager#35]
Not syncing at all on pov attached is log
![PXL_20240730_064625351](https://github.com/user-attachments/assets/e06a6cf5-3d86-4485-8fb6-d48b4c8cfe88)

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. I will push an update in the coming days to fix POV.

**Comment by Zaxxon709** [comment]
An update has been pushed to fix this issue v2.5.8
