### ISSUE TITLE
Seren and POV not sync correctly 

### ISSUE THREAD

**Issue by minhgi** [Zaxxon709/accountmanager#37]
Just two addon doesn't syn correctly.  FEN, FEN Lite, and Umbrella sync just and working.

Using Account Manger 2.5.7

**Comment by Zaxxon709** [comment]
An update has been pushed to fix this issue v2.5.8

**Comment by minhgi** [comment]
Hi Zaxxon....just want to update.  POV is fix but Seren still have issue.  If Seren was already authorized through Trakt website, sync it Account Manager actually revoke it.

**Comment by minhgi** [comment]
Thanks for the explanation.
