### ISSUE TITLE
Buffering and crashing

### ISSUE THREAD

**Issue by Marine661** [Zaxxon709/accountmanager#38]
My nvidia shield was working better than ever than all the sudden it starting buffering and crashing from one day to another. I have Kodi 21.0 and the cg man build with Superman.

**Comment by Zaxxon709** [comment]
Sorry, but this has nothing to do with Account Manager. You'll need to speak to the build developer and check your internet service. One thing that may help with your buffering would be to configure Kodi's video cache settings.

**Comment by Marine661** [comment]
Thanks for the info and your timeSent from my iPhone 15 PRO MAXGOD Bless those who paid the ultimate price so that I may live the life that I live.On Aug 19, 2024, at 9:41 AM, Zaxxon709 ***@***.***> wrote:﻿
Closed #38 as completed.
