### ISSUE TITLE
Genocide debrid authemtication

### ISSUE THREAD

**Issue by cg00001** [Zaxxon709/accountmanager#40]
Just tried -Chains- Genocide, and I had to use Genocide's settings to authenticate debrid.
Can you look it up? Trakt works fine as mentioned in your addons list, but it's absent from debrid list.
https://github.com/Zaxxon709/accountmanager#debrid

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. I'll have a look into it.

**Comment by Zaxxon709** [comment]
Update pushed which resolves this issue.
