### ISSUE TITLE
Developer keys

### ISSUE THREAD

**Issue by nebulous42069** [Zaxxon709/accountmanager#41]
So, I have been using developer keys in the builds as you suggested, however, I just realized something. Hear me out... So in order to save the logins in Account manager when updating a build, the build wizard must exclude account manager addon_data so it doesnt get wiped during a build update. This way the saved logins carry over after the build update. So without realizing, although the developer keys are added to AM before the build is zipped up, the wizard is excluding the AM addon_data , so the dev keys added before the zip never carry over. So really, when the dev keys reside in the addon_data settings.xml of AM and the wizard is excluding the AM addon_data, the dev keys never get used, unless a clear data is performed before install. So theres not really a way to have both the dev keys and logins saved if it works this way? So I was curious if it would make sense to have the dev keys written to the addon folder for AM instead of the addon_data folder? Since addon updates dont wipe the entire addon folder when updating, it usually just overwrites the files I think? So if the dev keys were written to a folder in the AM addon folder, that folder would stay intact when AM addon has an update.  Does this make sense? But llike I said, im not positive if updating an addon fully wipes the addon folder or if it overwrites whats there. If it does wipe it, maybe a custom location option in AM settings to store the dev keys would work? Then exclude that in the wizard? Hmm.

**Comment by Zaxxon709** [comment]
Just exclude Account Managers data_path in your wizard, problem solved. That's how it is supposed to function. You add the keys before zipping and exclude AM data_path in your wizard. 

The example below shows what your wizard's 'json' should look like. There is no need to add any add-ons that AM already supports. As you can see below, only AM is added.  If there are any that are not supported you can certainly add them there. 

How things will function - If the build is fresh installed the user will have to auth their Trakt account at first run which will use the Dev keys you have provided in the zip. For any future updates, the data_path will be excluded. Once an update is complete, AM will auth all supported add-ons included in your build at first run.

`{
    "favourites.xml": {
        "name": "Kodi_Favourites",
        "setting": "savefavs",
        "path": "user_path"
    },
    "advancedsettings.xml": {
        "name": "Kodi_AdvancedSettings",
        "setting": "saveadvanced",
        "path": "user_path"
    },
    "sources.xml": {
        "name": "Kodi_Sources",
        "setting": "savesources",
        "path": "user_path"
    },
    "script.module.accountmgr": {
        "name": "Account Manager",
        "setting": "savedata",
        "path": "data_path"
    },
    "plugin.video.imdb.trailers": {
        "name": "IMDb Trailers",
        "setting": "savedata",
        "path": "data_path"
    },
    "plugin.video.youtube": {
        "name": "YouTube",
        "setting": "saveyoutube",
        "path": "data_path"
    }
}`

**Comment by nebulous42069** [comment]
> Just exclude Account Managers data_path in your wizard, problem solved. That's how it is supposed to function. You add the keys before zipping and exclude AM data_path in your wizard.
> 
> The example below shows what your wizard's 'json' should look like. There is no need to add any add-ons that AM already supports. As you can see below, only AM is added. If there are any that are not supported you can certainly add them there.
> 
> How things will function - If the build is fresh installed the user will have to auth their Trakt account at first run which will use the Dev keys you have provided in the zip. For any future updates, the data_path will be excluded. Once an update is complete, AM will auth all supported add-ons included in your build at first run.
> 
> `{ "favourites.xml": { "name": "Kodi_Favourites", "setting": "savefavs", "path": "user_path" }, "advancedsettings.xml": { "name": "Kodi_AdvancedSettings", "setting": "saveadvanced", "path": "user_path" }, "sources.xml": { "name": "Kodi_Sources", "setting": "savesources", "path": "user_path" }, "script.module.accountmgr": { "name": "Account Manager", "setting": "savedata", "path": "data_path" }, "plugin.video.imdb.trailers": { "name": "IMDb Trailers", "setting": "savedata", "path": "data_path" }, "plugin.video.youtube": { "name": "YouTube", "setting": "saveyoutube", "path": "data_path" } }`

Yes, I understand that, and thats what my wizard is set to, but what I was trying to explain is that it wouldnt take effect unless a clear data is performed first. For example if the current build your using doesnt have the dev keys added yet, and the builder adds the keys to the next update, it wont apply since the wizard is saving and restoring the AM addon_data already and restoring the same settings.xml from the last installed build. I guess eventually if or when the clear data again it would show up but if the wizard is backing up and restoring it it never will without a clear data.

**Comment by nebulous42069** [comment]
Its not that big of a deal. Guess if you remove the backup function in the wizard for a few updates, eventually the dev keys will get written in..

**Comment by Zaxxon709** [comment]
> > Just exclude Account Managers data_path in your wizard, problem solved. That's how it is supposed to function. You add the keys before zipping and exclude AM data_path in your wizard.
> > The example below shows what your wizard's 'json' should look like. There is no need to add any add-ons that AM already supports. As you can see below, only AM is added. If there are any that are not supported you can certainly add them there.
> > How things will function - If the build is fresh installed the user will have to auth their Trakt account at first run which will use the Dev keys you have provided in the zip. For any future updates, the data_path will be excluded. Once an update is complete, AM will auth all supported add-ons included in your build at first run.
> > `{ "favourites.xml": { "name": "Kodi_Favourites", "setting": "savefavs", "path": "user_path" }, "advancedsettings.xml": { "name": "Kodi_AdvancedSettings", "setting": "saveadvanced", "path": "user_path" }, "sources.xml": { "name": "Kodi_Sources", "setting": "savesources", "path": "user_path" }, "script.module.accountmgr": { "name": "Account Manager", "setting": "savedata", "path": "data_path" }, "plugin.video.imdb.trailers": { "name": "IMDb Trailers", "setting": "savedata", "path": "data_path" }, "plugin.video.youtube": { "name": "YouTube", "setting": "saveyoutube", "path": "data_path" } }`
> 
> Yes, I understand that, and thats what my wizard is set to, but what I was trying to explain is that it wouldnt take effect unless a clear data is performed first. For example if the current build your using doesnt have the dev keys added yet, and the builder adds the keys to the next update, it wont apply since the wizard is saving and restoring the AM addon_data already and restoring the same settings.xml from the last installed build. I guess eventually if or when the clear data again it would show up but if the wizard is backing up and restoring the old settings.xml without the keys, it it never apply the new settings.xml with the keys newly added without a clear data first.

ok, now I understand what you're getting at. Let me think about it. I'm sure I can come up with a solution.

**Comment by nebulous42069** [comment]
I probably added dev keys a few months back and didnt realize they were never being used, since the wizard keeps backing the old settings up, lol. I never noticed since I just unzip the build fresh when testing and dont use the wizard to update..

**Comment by Zaxxon709** [comment]
Catch me on Telegram, I did msg you on there yesterday.
