### ISSUE TITLE
TMDb API Key - No Data Found!

### ISSUE THREAD

**Issue by Better-Red** [Zaxxon709/accountmanager#44]
Hi, thanks for the plug-in, I've just come back to it.

This might be my limited understanding, but when I go to Manage Accounts > Metadata Providers > View Authorisations I get the dialogue "TMDb API Key - No Data Found!" in all entries (POV, Absolution, TMDB Helper and Account Manager). All other API keys are syncing. My TMDb API key is saved in Account Manager as well as individually in POV and Absolution (I cannot find an entry for it in TMDB Helper). I also have an active TMDb session saved to Account Manager. This is using Account Manager v2.6.0 and Account Viewer v2.4.2 with Kodi 21.1 on both Windows 64-bit and Android 64-bit.

Thanks again!

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue and sorry for the delay in getting back to you. I've been quite busy. I will look into this as soon as I have time.

**Comment by Better-Red** [comment]
Much appreciated and no rush at all.

**Comment by Zaxxon709** [comment]
It looks like I found the issue. It's amazing what one incorrect character can do! Could you install the below via zip and let me know if this resolves the issue? If so, I'll include the fix in the next update. Thanks

[script.module.acctview.zip](https://github.com/user-attachments/files/17376946/script.module.acctview.zip)

**Comment by Better-Red** [comment]
Tell me about it, the numbers of times I haven't been able to get an apk to run and it's been a character in a line of code or an image out by a pixel. Anyway, that's got it, works perfectly, the TMDb API Key is now a lovely green colour! :)

**Comment by Zaxxon709** [comment]
> Tell me about it, the numbers of times I haven't been able to get an apk to run and it's been a character in a line of code or an image out by a pixel. Anyway, that's got it, works perfectly, the TMDb API Key is now a lovely green colour! :)

Ok...great! Thanks for testing. I'll include this fix in the next update.
