### ISSUE TITLE
There's no way to reauthorize an existing account

### ISSUE THREAD

**Issue by hyc** [Zaxxon709/accountmanager#46]
I revoked a debrid key at their website because I thought someone else had hacked it. Now I need a new authorization in accountmanager but it never gives me that option. Revoking in "Manage Accounts" doesn't do anything.

**Comment by Zaxxon709** [comment]
Just revoke and re-authorize you account via Account Manager.

**Comment by hyc** [comment]
I've tried that already, doesn't have any effect.

https://github.com/user-attachments/assets/117bda31-e819-46fd-a888-4dafd60333ae

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. Could you please install the below and let me know if your issue is resolved? Thanks

[script.module.acctview.zip](https://github.com/user-attachments/files/17565779/script.module.acctview.zip)

**Comment by hyc** [comment]
Sorry, I already forced it to reauthorize by editing `script.module.accountmgr/resources/settings.xml` and setting 
`<setting type="action" label="32319" option="close" action="RunScript(script.module.accountmgr, action=alldebridAuth)" visible="true" />`
