### ISSUE TITLE
Problems with real debrid authentication

### ISSUE THREAD

**Issue by ThuGMastaH** [Zaxxon709/accountmanager#47]
Hey man, I was watching fen lite this morning and all of a sudden it wouldn't load the next episode and after I did some messing around I figured out that when you click to authenticate real debrid nothing happens but a message will pop-up saying to check logs in account manager or something like that. If I click on any other debrid provider or trakt authentication links it provides the pop-up with the verification code. Not so with real debrid right now. Yes I am current on my real debrid service as well, anything else I can do? I can follow directions but not that tech savvy. Thanks for your time, jon

**Comment by Zaxxon709** [comment]
Reproduce the error and post the kodi log file here.

**Comment by ThuGMastaH** [comment]
I'm sorry I don't know how to. I'm using a nvidia shield pro.

**Comment by Zaxxon709** [comment]
Unfortunately, without a log I'm unable to confirm what's causing the error. 

I'd recommend clearing all authorizations and then reauthorize. To do this, open AM settings and go to the Advanced menu. Then choose 'Restore to Default Settings' and follow the prompts.

**Comment by ThuGMastaH** [comment]
Thanks for that, I tried and that did not do anything. I can send a pic of the screen and the unresponsive link is highlighted authenticate real debrid
![17317096136086179936867731392865](https://github.com/user-attachments/assets/62ce62f3-371b-4f78-b5af-a1272e85903b)

**Comment by ThuGMastaH** [comment]
It fails to bring up a screen like this when clicked and only brings up that pop-up in the lower right hand corner of first picture
![17317099146729015871538297920515](https://github.com/user-attachments/assets/fa91fbf8-e47c-45d6-b580-543b2e2de3dc)
This is what happens for authenticating premiumize

**Comment by Zaxxon709** [comment]
That menu is not part of AM. It looks like a menu from within a build. You should speak to the build developer about those shortcuts. 

To authorize, open AM settings and authorize you debrid account from there.

**Comment by Better-Red** [comment]
> It fails to bring up a screen like this when clicked and only brings up that pop-up in the lower right hand corner of first picture ! This is what happens for authenticating premiumize

That's Diggz Wizard, which if I remember correctly is a copy of Open Wizard. I doubt it's compatible with FEN Lite as the Open Wizard code predates FEN Lite by a few years. Apologies for going off topic.

**Comment by ThuGMastaH** [comment]
I got you...I thought you were the developer for the  build. Even going through the AM accounts screen when I select authorize under real debrid, it just backs out of the AM and no other pop-up screen appears with the numbers to enter like when I hit authorize under premiumize.  It's just one of those things. I appreciate your time and you gave me a few ideas to look into after a fresh install. Lol. Just now, through AM, it came up for RD after a long pause and when I entered the info, nothing happened and it remained basically frozen. I can not even duplicate it again after trying multiple times...   ok so it just happened again. I hit authorize and after about a minute the 2nd window popped up, then it disappeared after about 10-15 seconds it just disappeared and a banner in the top corner said Account Manager error. Anyway, appreciate your time. Maybe it will straighten itself out like it broke itself .. haha

**Comment by Rooman308** [comment]
I'm having the exact same issue with RD , I even factory reset my shield , and reloaded kodi and still the same issue , I installed kodi on my TV,  and it's still doing the same thing ! At least I'm not alone and feel like rd will resolve this ...

**Comment by ThuGMastaH** [comment]
I just signed up for a trial of alldebrid and although now that works, nothing will play. I don't have a clue what's up. It just started up when I was watching it this am and been trying to figure it out all day. Thought alldebrid would be the workaround for now but thats not working either...weird. stuff...good luck

**Comment by Zaxxon709** [comment]
> I just signed up for a trial of alldebrid and although now that works, nothing will play. I don't have a clue what's up. It just started up when I was watching it this am and been trying to figure it out all day. Thought alldebrid would be the workaround for now but thats not working either...weird. stuff...good luck

Power cycle your router.

I've tested RD via AM and there is no issue.

**Comment by Rooman308** [comment]
I'm wondering if it's something to do with the Tyson fight screwing up everything

**Comment by ThuGMastaH** [comment]
Lol...you know I gave up with everything for the night after a router restart and still nothing so I turned on Netflix and I kind of thought the same thing for like a split second...lol...I can't even get all debrid to work so I'm stumped and after a whole Lotta nothing, tired of it...I guess I'm watching Tyson tonight..haha

**Comment by Rooman308** [comment]
I'm hoping by tomorrow it will work again , I know the Tyson fight is being streamed through a pile of different sites through YouTube,  my guess is they are using any servers they can find and maybe including debrid. Enjoy the fight , I gave up my Netflix years ago unfortunately

**Comment by Zaxxon709** [comment]
@ThuGMastaH @Rooman308 Did you guys get the issue with RD sorted?

**Comment by ThuGMastaH** [comment]
I did not. I also have not had any success with all debrid allowing any links to play even though it says its authenticated. I still get the account manager error message when trying to do anything with RD.

**Comment by Zaxxon709** [comment]
Ok, I recommend you test using one of my builds. Go to the below URL and follow the instructions to install my repo/wizard. Once the wizard is installed you can open it and go to the build menu. Install Xlite Plus and authorize your accounts via the top bar menu under the wrench icon. If you want to install a K21 Fork then there is a link for that below as well.

Instructions
[https://github.com/Zaxxon709/zaxxon](url)

Repo
[https://zaxxon709.github.io/repo/](url)

K21 Fork
[https://dr-venture.com/apks/kodi/709Forks/](url)

**Comment by ThuGMastaH** [comment]
Ok cool. I appreciate that. I'll try that when I get back from getting my car inspected. I'm not sure what a k21 fork is and or if it's even needed. 
I just find it strange that I'm even having problems with all debrid as well. It looks like it should work but nothing ever plays.

**Comment by Zaxxon709** [comment]
> Ok cool. I appreciate that. I'll try that when I get back from getting my car inspected. I'm not sure what a k21 fork is and or if it's even needed. I just find it strange that I'm even having problems with all debrid as well. It looks like it should work but nothing ever plays.

I'm pretty confident this is an issue on your end or with RD in your area. I've seen multiple reports of issues with RD yesterday. I've tested and there is no issue with AM authorizing RD.

A Kodi fork is for Android users. It can be installed along side stock kodi. It also comes packed with my repo/wizard. Just install the fork and then open to install one of my builds. I create builds that are simple to use and very light weight.

**Comment by ThuGMastaH** [comment]
Thanks. I'll ck that out and let you know how I make out. I really appreciate your time and help.

**Comment by ThuGMastaH** [comment]
Just loaded up xlite version 8.2 I think and the trakt TV and all debrid synced right up but still unable to actually play anything with alldebrid and still can not authorize RD, error message still pops up saying AM error. I'm in upstate NY just FYI in case it's a regional thing...what would you say is the best build you have on here? And any other ideas on what I can do or try? Thanks again for everything

**Comment by ThuGMastaH** [comment]
![20241116_131523](https://github.com/user-attachments/assets/e902900f-02dd-4f5d-907d-d0de38621da8)

**Comment by ThuGMastaH** [comment]
Hey man just an update. I just tried to set up RD again and it worked just fine with the build I said I installed. Both all debrid and real debrid are pulling up viewable results. It does look like there may be something up with fen lite which kind of sucks, that's been my go to. Anyway I appreciate the help and patient advice. If you have any other hints tips or trick's I can do im all open to listen (like the fork thing, now I'm realizing why you said to add that first. Now I have to figure out how to undo it this way and do it the way you suggested. It was just frustrating last few days. Lol)...
Thanks again and enjoy the rest of the weekend.

**Comment by Zaxxon709** [comment]
Thanks for the update. Glad you got it sorted! I haven't had time to look into it further. I've been travelling the last few days with limited online  access. For Fen Light check to make sure you have the scraper module (cocoscrapers) enabled in settings. That may be your issue.

**Comment by Zaxxon709** [comment]
Thanks for the update. Glad you got it sorted! Sorry for the late response bu I've been travelling the last few days with limited online  access. 

I've seen multiple users reporting  issues with RD in the last couple days. This is not an issue with AM. The issue is most likely with your ISP or your network. The log shows issues reaching RD's api url. I haven't had time to look into it further. It's possible for some reason it's being blocked. For Fen Light check to make sure you have the scraper module (cocoscrapers) enabled in settings. That may be your issue.
