### ISSUE TITLE
Real debrid wont aithorise on shield OR Sony tv 

### ISSUE THREAD

**Issue by Rooman308** [Zaxxon709/accountmanager#48]
I factory reset my shield and reinstalled kodi and still having same issue. I can install addons but when I try to authenticate RD Nothing happens , or if I DO get the login code screen ( the odd time it does come up ) I type in the code to my phone and kodi does nothing at all , freezes up . 
![17317152858495042357651704806859](https://github.com/user-attachments/assets/492a08db-9152-4f98-8de4-b50c464bb636)
![17317153069352090794911456081162](https://github.com/user-attachments/assets/f3cae9ee-6986-44e9-9e48-3dd79881918e)
![17317153283431110340425349764803](https://github.com/user-attachments/assets/d3b91a97-1229-415e-a52f-1b7a45019664)
![17317153511546531041863821747262](https://github.com/user-attachments/assets/9f81f4c5-9b5e-4d53-8cbe-71678dba2894)
![17317153711784149700565869688752](https://github.com/user-attachments/assets/8a271de1-2d0c-4f62-83af-a01814ad08c2)
![17317153901102857767354569170005](https://github.com/user-attachments/assets/1e0323f2-e660-4bfe-bbb3-987f4026d776)

**Comment by Zaxxon709** [comment]
I just tested RD authentication and there is no issue. Could you test within stock Kodi, not a build?

**Comment by Rooman308** [comment]
I tried that using the crew , same problem . Is it something to do with the Tyson fight ??

**Comment by Zaxxon709** [comment]
No issue here. After seeing the log provided by a user it appears theissue is with either your ISP or network. For some reason the api url is unreachable.
