### ISSUE TITLE
Nothing is downloading on my real debrid or all debrid

### ISSUE THREAD

**Issue by Dawnsteffek123** [Zaxxon709/accountmanager#49]

**Comment by Dawnsteffek123** [comment]
It just spins and pops back to show title

**Comment by Zaxxon709** [comment]
Sorry, I would need a better description of the issue. I'd suspect you're experiencing the same issue as other users have in the last couple days. From the log it appears RD's api is being blocked by either your ISP or there is an issue with your network. You could start with a power cycle of your router.
