### ISSUE TITLE
MDBlist compatibilty for the Nimbus (and FENtastic) skins

### ISSUE THREAD

**Issue by Better-Red** [Zaxxon709/accountmanager#58]
Hi, Would it be possible to add MDBlist compatibility for the Nimbus skin? FENtastic would be great too, but the skin isn't in active development. It's a pain trying to re-enter the MDBlist API to the skin settings after a build update. Many thanks.

**Comment by Zaxxon709** [comment]
Fentastic and Nimbus mdblist support has been added to the latest update v2.6.2. Cheers

**Comment by Better-Red** [comment]
Much appreciated, thank you!

**Comment by Better-Red** [comment]
Apologies for reopening, MDblist sync is working great in FENtastic and it was in Nimbus. Nimbus no longer works (for me - multiple devices). I don't know if it's relevant, but Nimbus was updated to v0.1.31.

**Comment by Zaxxon709** [comment]
No need to open another issue. I'll have a look when I get some free time.
