### ISSUE TITLE
Enable external scraper for ezra Ultra 2 box

### ISSUE THREAD

**Issue by JVAV05** [Zaxxon709/accountmanager#59]
I revoked real-debrid and then enabled premiumize. Once I did that I was no longer able to watch anything it just says "no external scrapers enabled". I did the same thing on my other box, except I didn't revoke real-debrid first, and everything works great???

**Comment by rizreflects** [comment]
Have you installed cocoscrapers? You need to install it and then enable it in Ezra's settings. Sounds like an issue with Ezra rather than account manager. With that being said, Ezra is an old addon that's no longer maintained. Install Fen light, umbrella or POV.

**Comment by Zaxxon709** [comment]
Ezra is no longer supported. It was removed in the last update.

Like @rizreflects  mentioned, this addon has not been supported for quite some time. That's why it was removed from AM. You should look at using one of the addons suggested above.

**Comment by JVAV05** [comment]
I tried downloading Fen light because that is one I could find. That didn't
really work for me.

I tried using Asgard, ghost, majig dragon... and some of the other players
and I can watch stuff on those. But when I sync my Trakt account to them,
they go to my Trakt list but when I click on a list it just says Asgard (or
whatever player I used) error. Any ideas as to what is wrong?

Thanks

**Comment by rizreflects** [comment]
Let's stick to Fen light. Which version of Fen light are you using? Did you install cocoscrapers and enable it as an external scraper in fen lights settings?
