### ISSUE TITLE
Resolveurl addons

### ISSUE THREAD

**Issue by nebulous42069** [Zaxxon709/accountmanager#7]
Some of the addons that use ResolveURL show up as not authorized in the view authorized addons section. Since they dont have their own debrid authorization, maybe they shouldn't be in the list anyways? Like Magic Dragon, shadow, etc.

**Comment by Zaxxon709** [comment]
Thanks for reporting the issue. This is already on my to do list. Unfortunately, I have no control over add-on devs changing how their add-ons function, so issues like this will occasionally popup and require editing. At the moment I'm quite busy but I will be looking at pushing an update in the coming weeks.

**Comment by Zaxxon709** [comment]
It appears Shadow and some of its forks work fine with RD authed via ResolveURL but not with other services.  Shadow Forks are tricky as each one is forked from a different version. I'm leaving these included in 'View Authorized Add-ons', for now.
