### ISSUE TITLE
Fen and Ezra Error

### ISSUE THREAD

**Issue by casedup** [Zaxxon709/accountmanager#9]
Having the same problem I had before using the app where Ezra and Fen doesn't seem to like my Trakt API settings. I fixed this error before by Enabling Meta Providers and filling in necessary stuff however installed into a new setup and getting the same error I fixed before even though now I have the meta settings enabled.

**Comment by Zaxxon709** [comment]
Could you provide a log including the error, please? Are you using your own personal API keys?
